<?php
// +----------------------------------------------------------------------
// | 百灵中枢插件安装脚本
// | composer install/update 后自动执行：把包内 src/ 复制到 CRMEB app/bailing/
// | 注意：用复制而非软链——Docker bind mount 场景下软链在容器内会失效
// +----------------------------------------------------------------------

$rootDir = findRoot(__DIR__);                // CRMEB 项目根（向上找同时含 app/ 和 vendor/ 的目录）
if (!$rootDir) {
    failInstall('无法定位 CRMEB 项目根目录，请确认本脚本位于 vendor/crmeb/bailinghub/scripts/ 下');
}
$pkgDir = $rootDir . '/vendor/crmeb/bailinghub';
$appDir = $rootDir . '/app';

/**
 * 向上查找 CRMEB 项目根（同时含 app/ 与 vendor/ 的目录）
 * 不能写死层级数：vendor 包路径深度可能变化
 */
function findRoot($start)
{
    $dir = $start;
    for ($i = 0; $i < 6; $i++) {
        if (is_dir($dir . '/app') && is_dir($dir . '/vendor')) {
            return $dir;
        }
        $dir = dirname($dir);
    }
    return null;
}

// 目标应用目录（think-multi-app 约定：URL /bailing/* 由 app/bailing/ 处理）
$targetAppDir = $appDir . '/bailing';
$srcDir = $pkgDir . '/src';

if (!is_dir($srcDir)) {
    failInstall("src 目录不存在: $srcDir");
}

// 先复制到同一文件系统的临时目录，再切换；复制失败时旧运行目录保持不动。
deployApplicationCopy($srcDir, $targetAppDir);
echo "[bailinghub] 已复制应用代码到 app/bailing/\n";

// 刷新插件自有配置文件。运行值在 system_config / SecretStore，不写进此 PHP 文件；
// 必须覆盖旧生成文件，才能移除历史版本中的 secret sys_config 读取代码。
$configSrc = $pkgDir . '/config/bailing.php';
$configDst = $rootDir . '/config/bailing.php';
if (is_file($configSrc)) {
    installConfigFile($configSrc, $configDst);
}

// 注册 ThinkPHP 服务（BailingService 负责路由注册 + 后台配置项 + 聊天组件注入）
// 首选 service:discover（CRMEB composer post-autoload-dump 会自动执行），
// 失败时（如服务器无 composer 环境、手动 zip 安装）直接补写 vendor/services.php
ensureServiceRegistered($rootDir);

echo "[bailinghub] 安装完成。后续步骤：\n";
echo "  1. 后台「系统设置 → 百灵中枢配置」优先粘贴完整聊天入口嵌入代码，并填写 token/签名密钥\n";
echo "  2. 在 BailingHub 中枢控制台登记工具源：\n";
echo "     spec_url = {你的域名}/bailing/tools.json\n";
echo "     base_url = {你的域名}（源站直连地址，勿走会重写 URI 的 CDN/网关）\n";
echo "     access_policy = signed_required（签名密钥与 CRMEB 后台一致）\n";
echo "  3. 手工安装或首次桥接完成后，请重载站点实际使用的 PHP-FPM（或重启 PHP 容器），再重新登录并强制刷新 CRMEB 后台\n";

/**
 * 确保 app\bailing\BailingService 出现在 vendor/services.php
 */
function ensureServiceRegistered($rootDir)
{
    $servicesFile = $rootDir . '/vendor/services.php';
    $serviceClass = 'app\\\\bailing\\\\BailingService';

    // 已注册则跳过
    if (is_file($servicesFile)) {
        $content = file_get_contents($servicesFile);
        if (strpos($content, 'BailingService') !== false) {
            echo "[bailinghub] 服务已注册（vendor/services.php）\n";
            return;
        }
    }

    // 优先走官方服务发现
    $thinkCli = $rootDir . '/think';
    if (is_file($thinkCli)) {
        @exec('php ' . escapeshellarg($thinkCli) . ' service:discover 2>&1', $out, $code);
        if (is_file($servicesFile) && strpos(file_get_contents($servicesFile), 'BailingService') !== false) {
            echo "[bailinghub] 服务已通过 service:discover 注册\n";
            return;
        }
    }

    // 兜底：直接补写 services.php（保持原数组结构，仅追加一行）
    if (is_file($servicesFile)) {
        $content = file_get_contents($servicesFile);
        // 在最后的 ");" 前插入一行
        $pos = strrpos($content, ');');
        if ($pos !== false) {
            $entry = "  99 => '" . $serviceClass . "',\n";
            $content = substr($content, 0, $pos) . $entry . substr($content, $pos);
            if (file_put_contents($servicesFile, $content) === false) {
                failInstall('无法更新 vendor/services.php');
            }
            echo "[bailinghub] 服务已补写到 vendor/services.php\n";
            return;
        }
    }
    // 文件不存在则新建
    if (file_put_contents($servicesFile, "<?php \n// generated by crmeb/bailinghub install\ndeclare (strict_types = 1);\nreturn array (\n  99 => '" . $serviceClass . "',\n);\n") === false) {
        failInstall('无法创建 vendor/services.php');
    }
    echo "[bailinghub] 已创建 vendor/services.php 并注册服务\n";
}

/** 原子刷新插件生成的 config/bailing.php；拒绝符号链接和非普通目标。 */
function installConfigFile($source, $destination)
{
    if (is_link($destination) || (file_exists($destination) && !is_file($destination))) {
        failInstall('config/bailing.php 不是普通文件，拒绝覆盖');
    }
    if (is_file($destination)
        && hash_equals((string)hash_file('sha256', $source), (string)hash_file('sha256', $destination))) {
        echo "[bailinghub] 配置文件已是最新: config/bailing.php\n";
        return;
    }
    $temporary = dirname($destination) . '/.bailing-config-' . str_replace('.', '', uniqid('', true));
    if (!copy($source, $temporary)) {
        failInstall('无法创建配置文件候选副本: config/bailing.php');
    }
    @chmod($temporary, 0644);
    if (!rename($temporary, $destination)) {
        @unlink($temporary);
        failInstall('无法原子刷新配置文件: config/bailing.php');
    }
    echo "[bailinghub] 已刷新配置文件: config/bailing.php\n";
}


function recurseCopy($src, $dst)
{
    if (!is_dir($dst) && !mkdir($dst, 0755, true)) {
        throw new RuntimeException('无法创建目录: ' . $dst);
    }
    $dir = opendir($src);
    if ($dir === false) {
        throw new RuntimeException('无法读取目录: ' . $src);
    }
    while (false !== ($file = readdir($dir))) {
        if ($file != '.' && $file != '..') {
            if (is_dir($src . '/' . $file)) {
                recurseCopy($src . '/' . $file, $dst . '/' . $file);
            } else {
                if (!copy($src . '/' . $file, $dst . '/' . $file)) {
                    closedir($dir);
                    throw new RuntimeException('无法复制文件: ' . $src . '/' . $file);
                }
            }
        }
    }
    closedir($dir);
}

function recurseRemove($dir)
{
    if (is_link($dir) || is_file($dir)) {
        if (!unlink($dir)) {
            throw new RuntimeException('无法删除路径: ' . $dir);
        }
        return;
    }
    if (!is_dir($dir)) {
        return;
    }
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($it as $file) {
        $ok = $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
        if (!$ok) {
            throw new RuntimeException('无法删除路径: ' . $file->getPathname());
        }
    }
    if (!rmdir($dir)) {
        throw new RuntimeException('无法删除目录: ' . $dir);
    }
}

/**
 * 原子刷新 app/bailing：先完整构建候选副本，再保留旧目录并切换。
 */
function deployApplicationCopy($srcDir, $targetAppDir)
{
    $parent = dirname($targetAppDir);
    $suffix = str_replace('.', '', uniqid('', true));
    $stage = $parent . '/.bailing-stage-' . $suffix;
    $backup = $parent . '/.bailing-backup-' . $suffix;

    try {
        recurseCopy($srcDir, $stage);
        $hadCurrent = is_dir($targetAppDir) || is_link($targetAppDir) || is_file($targetAppDir);
        if ($hadCurrent && !rename($targetAppDir, $backup)) {
            throw new RuntimeException('无法备份现有 app/bailing 目录');
        }
        if (!rename($stage, $targetAppDir)) {
            if ($hadCurrent && file_exists($backup)) {
                @rename($backup, $targetAppDir);
            }
            throw new RuntimeException('无法切换新的 app/bailing 目录');
        }
        if ($hadCurrent && file_exists($backup)) {
            recurseRemove($backup);
        }
    } catch (Throwable $e) {
        if (file_exists($stage)) {
            try {
                recurseRemove($stage);
            } catch (Throwable $ignored) {
            }
        }
        if (!file_exists($targetAppDir) && file_exists($backup)) {
            @rename($backup, $targetAppDir);
        }
        failInstall($e->getMessage());
    }
}

function failInstall($message)
{
    fwrite(STDERR, '[bailinghub] 安装失败：' . $message . PHP_EOL);
    exit(1);
}
